### ISSUE TITLE
fail: Microsoft.AspNetCore.Server.Kestrel[13] error on dotnet run

### ISSUE THREAD

**Issue by BryanWilhite** [BryanWilhite/Songhay.Blog#18]
```bash:
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLFHR51IIUV2", Request id "0HLFHR51IIUV2:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.
Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.

   at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.<Attach>b__1(HttpContext context, Func`1 next)
   at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_1.<Use>b__1(HttpContext context)
   at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_2.<Use>b__2()
   at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_1.<Use>b__1(HttpContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
```

**Comment by BryanWilhite** [comment]
this is .NET Core issue as this same error occurs on Windows

**Comment by BryanWilhite** [comment]
the `"profiles"` dictionary in `launchSettings.json` has two profiles:

```json
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "Songhay.Blog": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "http://localhost:50323/"
    }
  }
```

in VS Code ` "IIS Express"` does _not_ work (throws “not supported” error) and the `"Songhay.Blog"` profile starts _NG Live Development Server_ which does not support ASP.NET Core; i know that VS Code can run ASP.NET Core but the current project configuration may be preventing this

**Comment by BryanWilhite** [comment]
i see now that `dotnet run` is no different from `npm start` (and would very much like to be mistaken); as a workaround, i see that i need to go through the VSCode F5 experience based on the auto-generated `launch.json`—however, because i have customized `tasks.json`, i need to make a change to `"preLaunchTask"` in `launch.json`

**Comment by BryanWilhite** [comment]
after getting guidance from [my StackOverflow answer](https://stackoverflow.com/a/51530307/22944), i see that [line 91](https://github.com/BryanWilhite/Songhay.Blog/blob/master/Songhay.Blog/Startup.cs#L91) of `Startup.cs` makes my previous statement, ‘i see now that `dotnet run` is no different from `npm start`,’ a true statement:

![image](https://user-images.githubusercontent.com/5226627/43274420-030ca832-90b4-11e8-9085-68a2d511a24c.png)

commenting this line out would require me to run `npm build` before running `npm run`

**Comment by BryanWilhite** [comment]
i suppose this issue is resolved in terms of me paying attention to this line of code: `spa.UseAngularCliServer(npmScript: "start")`

however, the default behavior of `Microsoft.DotNet.Web.Spa.ProjectTemplates::2.0.0` is to bypass Kestrel when `env.IsDevelopment() == true`
