### ISSUE TITLE
`ng test` error: ..\Songhay.Blog\Songhay.Blog\ClientApp\src\karma.conf.js does not exist

### ISSUE THREAD

**Issue by BryanWilhite** [BryanWilhite/Songhay.Blog#47]
```console
ng test

31 12 2018 14:13:31.046:ERROR [config]: File ..\Songhay.Blog\Songhay.Blog\ClientApp\src\karma.conf.js does not exist!
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! songhay.blog@2.0.0 test: `ng test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the songhay.blog@2.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

`*.debug.log` detail:

```console
9 verbose lifecycle songhay.blog@2.0.0~test: CWD: ..\Songhay.Blog\Songhay.Blog\ClientApp
10 silly lifecycle songhay.blog@2.0.0~test: Args: [ '/d /s /c', 'ng test' ]
11 silly lifecycle songhay.blog@2.0.0~test: Returned: code: 1  signal: null
12 info lifecycle songhay.blog@2.0.0~test: Failed to exec test script
13 verbose stack Error: songhay.blog@2.0.0 test: `ng test`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (..\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (..\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid songhay.blog@2.0.0
15 verbose cwd ..\Songhay.Blog\Songhay.Blog\ClientApp
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "..\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
18 verbose node v10.14.2
19 verbose npm  v6.5.0
20 error code ELIFECYCLE
21 error errno 1
22 error songhay.blog@2.0.0 test: `ng test`
22 error Exit status 1
23 error Failed at the songhay.blog@2.0.0 test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by BryanWilhite** [comment]
I have moved `karma.conf.js` to the location specified in the above error and got a new error:

```console
ng test

31 12 2018 14:26:23.614:ERROR [config]: Error in config file!
 Error: In Angular CLI >6.0 the Karma plugin is now exported by "@angular-devkit/build-angular" instead.
Please replace "@angular/cli" with "@angular-devkit/build-angular" in your "karma.conf.js" file.
```

```javascript
// Karma configuration file, see link for more information
// https://karma-runner.github.io/1.0/config/configuration-file.html

module.exports = function (config) {
    config.set({
        basePath: '',
        frameworks: ['jasmine', '@angular/cli'],
        plugins: [
            require('karma-jasmine'),
            require('karma-chrome-launcher'),
            require('karma-jasmine-html-reporter'),
            require('karma-coverage-istanbul-reporter'),
            require('@angular/cli/plugins/karma')
        ],
        client: {
            clearContext: false // leave Jasmine Spec Runner output visible in browser
        },
        coverageIstanbulReporter: {
            reports: ['html', 'lcovonly'],
            fixWebpackSourcePaths: true
        },
        angularCli: {
            environment: 'dev'
        },
        reporters: ['progress', 'kjhtml'],
        port: 9876,
        colors: true,
        logLevel: config.LOG_INFO,
        autoWatch: true,
        browsers: ['Chrome'],
        singleRun: false
    });
};
```

**Comment by BryanWilhite** [comment]
edited ``; getting new error:

```console
ERROR in node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
node_modules/rxjs/ReplaySubject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/ReplaySubject'.
src/app/mocks/services/activated-route-mock.ts(1,10): error TS2305: Module '"../Songhay.Blog/Songhay.Blog/ClientApp/node_modules/rxjs/Observable"' has no exported member 'Observable'.
src/app/mocks/services/activated-route-mock.ts(2,10): error TS2305: Module '"../Songhay.Blog/Songhay.Blog/ClientApp/node_modules/rxjs/ReplaySubject"' has no exported member 'ReplaySubject'.
```

**Comment by BryanWilhite** [comment]
from https://github.com/BryanWilhite/Songhay.Dashboard/issues/45#issuecomment-450697827:
```console
npm install --save rxjs-compat
npm rebuild node-sass
```
new error:
```console
ERROR in ./src/polyfills.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: ..\Songhay.Blog\Songhay.Blog\ClientApp\src\polyfills.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (..\Songhay.Blog\Songhay.Blog\ClientApp\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\angular_compiler_plugin.ts:978:15)
    at plugin.done.then (..\Songhay.Blog\Songhay.Blog\ClientApp\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\loader.ts:49:29)
    at process._tickCallback (internal/process/next_tick.js:68:7)
 @ multi ./src/polyfills.ts ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/jit-polyfills.js polyfills[0]
```
